### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by dga4130-renato** [jellyfin/jellyfin-plugin-reports#21]
ubuntu 19.10 
installing this plugin jellyfin 10.5. nightly crashes
if you remove the plugin from the plugins /var/lib/jellyfin/plugins the server starts ok
Version 4.0 is ok
[bug.txt](https://github.com/jellyfin/jellyfin-plugin-reports/files/4399024/bug.txt)

**Comment by dga4130-renato** [comment]
Can this be fixed ? this plugin is really usefull, thanks

**Comment by dga4130-renato** [comment]
Seems looking for 10.5.2 version of jellyfin, but the nightly version is still marked with 10.5.0, maybe that is a cause.

**Comment by dkanada** [comment]
I believe this is the cause.

**Comment by dga4130-renato** [comment]
I opend a ticket on the main jellyfin github about this but for now it's still there, if you feel  push this fix up close the two tickets then. thankssssss

**Comment by dga4130-renato** [comment]
Crash is solved but plugin is still not installing
