### ISSUE TITLE
Item count for media types only goes to 999

### ISSUE THREAD

**Issue by jcdick1** [jellyfin/jellyfin-plugin-reports#39]
Looking at my Reports plugin for movies, any page shows "X - Y of 999" so I'm guessing that's the maximum items it can handle of any given media type.  That needs to be bumped up to something probably pretty high.

JF 10.6.4 with Reports plugin v 10.0.0.0

**Comment by AlfredJKwack** [comment]
This is not an issue in v 12.0.0.0

<img width="495" alt="Screen Shot 2022-05-03 at 21 21 14" src="https://user-images.githubusercontent.com/557102/166540177-f98033dd-61ca-4db1-bf3d-c93caa6477c0.png">

This issue could be closed.
