### ISSUE TITLE
Reports Plugin Not working in 10.7.0

### ISSUE THREAD

**Issue by gwenvador** [jellyfin/jellyfin-plugin-reports#44]
This plugin is not working for 10.7.0. A previous ticket has been closed without resolution. It is still an issue: https://github.com/jellyfin/jellyfin-plugin-reports/issues/40.

**Comment by undead9786** [comment]
Same issue here.
If I downgrade to 10.6.4 and install Report 10.0.0.0 no issues but when I am on 10.7.0 Report 10.0.0.0 states notsupported and updating it to 11.0.0.0 doesn't work.

**Comment by SuperDavester** [comment]
I confirm, same issue with 10.7.1. Last

**Comment by SuperDavester** [comment]
This is the error I can see in the Firefox console once I click on the report page link from the Jellyfin dashboard:

Uncaught ReferenceError: define is not defined
    <anonymous> https://test.mysite.net/web/configurationpage?name=reportsjs:1
configurationpage:1:1

**Comment by whalehub** [comment]
@crobibero This plugin [currently depends on](https://github.com/jellyfin/jellyfin-plugin-reports/blob/539ea9c2a8064d894bffeb67373e63346e34c401/Jellyfin.Plugin.Reports/Web/reports.js#L1-L2) the RequireJS feature `define()`. RequireJS was [removed from Jellyfin Web](https://github.com/jellyfin/jellyfin-web/commit/67adeef13147117ee639f3e3109bef2d1a061740) in 10.7.0, which is probably the reason why the plugin has stopped working.

**Comment by crobibero** [comment]
Thank you for the ping, I was already aware of this change. The reports plugin is it's own beast that I haven't had proper time to tackle yet

**Comment by mastercho** [comment]
in v10.7.2 still not fixed , keeping eye here for fix

**Comment by whalehub** [comment]
@crobibero Can you please publish a new release that includes #46?

**Comment by crobibero** [comment]
> @crobibero Can you please publish a new release that includes #46?

After 10.7.6 is released, yes.

**Comment by whalehub** [comment]
@crobibero Jellyfin v10.7.6 is out: https://github.com/jellyfin/jellyfin/releases/tag/v10.7.6
