### ISSUE TITLE
Reports plugin not working in 10.8.1

### ISSUE THREAD

**Issue by zhujy09** [jellyfin/jellyfin-plugin-reports#71]
Reports plugin not working in 10.8.1
Server running on windows 11

**Comment by funkybunch** [comment]
Issues from #67 were not resolved in 10.8.1.  I suggest we pick a thread and track this issue under a single ticket - @zhujy09 mind chiming in on #67 and closing this issue?.

**Comment by zhujy09** [comment]
Closing this issue as requested.
